language: ruby
rvm:
  - 2.3.0
script: 
  - RAILS_ENV=test bundle exec rake db:migrate --trace
env:
  - DB=pgsql
services:
notifications:
  email: false
  - postgresql
before_script:
  - psql -c 'create database angular_todo_test;' -U postgres