default: &default
  adapter: postgresql
  template: template0
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: angular_todo_development
  username: postgres
  password: 123

test:
  <<: *default
  database: angular_todo_test
  username: postgres
  password: 123

production:
  <<: *default
  database: angular_todo_production
  username: angular_todo
  password: <%= ENV['ANGULAR_TODO_DATABASE_PASSWORD'] %>